Update package.json
There is an issue when trying to use this with vite-ssg:
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/mykolas/Documents/Projects/the_cheat/.vite-ssg-temp/main.mjs:29
import hljsVuePlugin from "@highlightjs/vue-plugin";
       ^^^^^^^^^^^^^
SyntaxError: The requested module '@highlightjs/vue-plugin' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async build (/Users/mykolas/Documents/Projects/the_cheat/node_modules/.pnpm/vite-ssg@0.17.10_2a1f4eb68d7efe0f1402d91afc414ace/node_modules/vite-ssg/dist/node/cli.cjs:180:87)
    at async Object.handler (/Users/mykolas/Documents/Projects/the_cheat/node_modules/.pnpm/vite-ssg@0.17.10_2a1f4eb68d7efe0f1402d91afc414ace/node_modules/vite-ssg/dist/node/cli.cjs:314:3)
```

Adding these exports fixes it.